//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantsType
    {
        public ApplicantsType()
        {
            this.People = new HashSet<Men>();
        }
    
        public int ID { get; set; }
        public string Applicant { get; set; }
    
        public virtual ICollection<Men> People { get; set; }
    }
}
