//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Men
    {
        public Men()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public string ID { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string ThirdName { get; set; }
        public string FamilyName { get; set; }
        public string Mobile { get; set; }
        public string EMail { get; set; }
        public int ApplicantsTypeID { get; set; }
    
        public virtual ApplicantsType ApplicantsType { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
