//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketStatu
    {
        public TicketStatu()
        {
            this.TicketDetails = new HashSet<TicketDetail>();
        }
    
        public int TicketStatusId { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<TicketDetail> TicketDetails { get; set; }
    }
}
