//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public Ticket()
        {
            this.TicketDetails = new HashSet<TicketDetail>();
        }
    
        public int ID { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public System.DateTime Date { get; set; }
        public int TicketTypeTickeTypeId { get; set; }
        public string PersonID { get; set; }
    
        public virtual Men Person { get; set; }
        public virtual ICollection<TicketDetail> TicketDetails { get; set; }
        public virtual TicketType TicketType { get; set; }
    }
}
